"""Add subscription, plan

Revision ID: bcc988144db1
Revises: 137ce27e60cd
Create Date: 2025-12-30 21:47:23.986475

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "bcc988144db1"
down_revision: Union[str, Sequence[str], None] = "137ce27e60cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
